name: Translate App - PR Management
on:
  workflow_call:
    inputs:
      startCicd:
        type: boolean
        default: false
    secrets:
      GHTOKENWORKFLOW:
        required: false
defaults:
  run:
    shell: pwsh
jobs:
  PRManagement:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHTOKENWORKFLOW }}
      - run: Write-Host "PR management"
      - if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.startCicd == true)
        run: Write-Host "Dispatch CI/CD"
